# Generated by Django 5.1.2 on 2024-11-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybuy', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
